# Generated by Django 3.0.5 on 2022-05-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispenseInfo', models.CharField(max_length=255)),
                ('saleInfo', models.CharField(max_length=255)),
                ('deviceInfo', models.CharField(max_length=255)),
                ('userInfo', models.CharField(max_length=255)),
                ('rfidInfo', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
